name: Upload to thunderstore

on:
  release:
    types: [published]
permissions:
  contents: read

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - name: checkout without tags
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # this retrieves tags AND history, not good

    - name: Zip up modpack
      run: |
        cd modpack
        zip -r modpack.zip .

    - validate

    - name: Publish package
      if: github.event_name == 'release'