name: Upload to thunderstore

on:
  release:
    types: [published]
permissions:
  contents: read

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: pickup number of commits
      run: export COMMIT_COUNT=1
      # $(git rev-list --count main)

    - name: generate manifest
      run: python -m lethal_whalers update-manifest

    - name: Zip up modpack
      run: |
        cd modpack
        zip -r modpack.zip .
        mv modpack.zip ..

    # TODO - validate

    - name: Publish package
      run: python -m lethal_whalers upload-modpack